[package]
name = "server"
version = "0.1.0"
authors = ["Gavin Capriola <@gavincapriola>"]
edition = "2021"
repository = "https://github.com/gavincapriola/server"
license = "Unlicense"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
